### ISSUE TITLE
Issues installing XDebug on php5.6-alpine

### ISSUE THREAD

**Issue by gdsmith** [mlocati/docker-php-extension-installer#771] opened 2023-06-28 17:40 UTC
### Version of install-php-extensions

v.2.1.35

### Error description

It seems like `pecl` is now broken on the alpine image for php5.6 so I'm trying to install xdebug from source but keep getting an error:

```
### INSTALLING REMOTE MODULE xdebug ###
  (installing version 2.5.5 from /tmp/src/tmp.bPPpOE/xdebug-XDEBUG_2_5_5)
ERROR: file /tmp/src/tmp.bPPpOE/xdebug-XDEBUG_2_5_5/debugclient/config.h.in does not exist
```

I've tried using version tags rather than using the source URL but neither seem to make a difference.

Running the following from the downloaded directory does seem to work:

```
./configure --enable-xdebug && \
	make && \
	make install
```

Any ideas what I should be doing differently here? Or even any ideas how to get `pecl` working again?

Let me also just say a big thank you for this tool, it's a fantastic resource for PHP devs working with Docker.

### Docker image

php5.6-alpine

### Minimal Dockerfile

```Dockerfile
RUN curl -sSLf \
         -o /usr/local/bin/install-php-extensions \
         https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions && \
     chmod +x /usr/local/bin/install-php-extensions && \
     install-php-extensions  https://codeload.github.com/xdebug/xdebug/tar.gz/refs/tags/XDEBUG_2_5_5
```
```

**Comment by mlocati** [comment] 2023-06-28 17:42
This is a duplicate of https://github.com/mlocati/docker-php-extension-installer/issues/770

**Closed by mlocati** 2023-06-28 17:42 UTC
Labels: bug

**Comment by gdsmith** [comment] 2023-06-28 20:57
Hi @mlocati thanks for the quick response, I don't believe this is related to the TLS issues you referenced. What I'm trying to do is install from source and that is somehow failing for `xdebug` (`install-php-extensions xdebug/xdebug@XDEBUG_2_5_5`) which seems to behave differently to `memcached` (`install-php-extensions php-memcached-dev/php-memcached@2.2.0`) for example. Is there something custom about how `xdebug` is handled that I can disable to get it to install?

**Comment by mlocati** [comment] 2023-06-28 21:41
I think it may be how the web servers that provide the files are configured.
Maybe one has enabled older tls versions (which work with old Alpine versions), and the other only supports tls 1.2 (which may not be supported by old Alpine versions).

But I'm just speculating. If you ever find the reason (and possibly the solution), please let me  know.
