### ISSUE TITLE
PHP 8.1 install/build fails for pdo_mysql & mysqli fails

### ISSUE THREAD

**Issue by typoworx-de** [mlocati/docker-php-extension-installer#698] opened 2023-02-22 12:45 UTC
### Version of install-php-extensions

install-php-extensions pdo_mysql mysqli

### Error description

For pdo_mysql:
```
#0 10.33 running: make
#0 10.33 Makefile:243: warning: overriding recipe for target 'test'
#0 10.33 Makefile:136: warning: ignoring old recipe for target 'test'
#0 10.34 make: *** No rule to make target 'pdo_mysql', needed by 'all'.  Stop.
#0 10.34 ERROR: `make' failed
```
and for mysql standalone (commented out line ```RUN install-php-extensions pdo_mysql```):
```
#0 9.523 running: make
#0 9.526 Makefile:243: warning: overriding recipe for target 'test'
#0 9.526 Makefile:136: warning: ignoring old recipe for target 'test'
#0 9.534 make: *** No rule to make target 'mysqli', needed by 'all'.  Stop.
#0 9.535 ERROR: `make' failed
```

### Docker image

php:8.1-fpm-bullseye (also tested: php:8.1-fpm-buster)

### Minimal Dockerfile

```Dockerfile
# syntax = docker/dockerfile:1.4.0
FROM php:8.1-fpm-bullseye

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN set -ex; \
  apt-get update \
  && apt-get -y upgrade \
    
RUN install-php-extensions pdo_mysql
RUN install-php-extensions mysqli
```

**Comment by typoworx-de** [comment] 2023-02-22 15:32
Fiddling around and now got this:
failed running [/bin/bash -c set -ex;   install-php-extensions pdo pdo_mysql mysqli]: exit code: 2

```
#0 7.844 pdo_mysql.c:22:10: fatal error: php.h: No such file or directory
#0 7.844    22 | #include "php.h"
#0 7.844       |          ^~~~~~~
#0 7.844 compilation terminated.
#0 7.845 make: *** [<builtin>: pdo_mysql] Error 1
```

Anybody has a clue how to fix this?

php-headers seem to be present, but somehow they are not correctly linked or present for install-php-extensions:
```
$ find / -type f -iname 'php.h'
...
/usr/local/include/php/main/php.h
/usr/src/php/main/php.h
```

**Comment by typoworx-de** [comment] 2023-02-22 17:13
Obvisouly prepending this in Dockerfile helps to resolve the missing PHP-Headers (php.h):
`RUN docker-php-source extract`

and finally to clean-up:
`RUN docker-php-source delete`

**Comment by mlocati** [comment] 2023-02-22 23:19
> Obvisouly prepending this in Dockerfile helps to resolve the missing PHP-Headers (php.h):
> `RUN docker-php-source extract`

[It's already included in the script](https://github.com/mlocati/docker-php-extension-installer/blob/2.0.5/install-php-extensions#L3969).

**Comment by typoworx-de** [comment] 2023-02-23 11:32
@mlocati thanks for your quick reply here. Good to know you already included it. It's really strange and annoying that it's not working for me. I'm already testing the whole build as simple as possible (without multi-build), but still it looks like the php extension libs are missing after build.

Executing the same commands like in build manually in the running container works! I must have something really strange/stupid mistake somewhere ... already wasted hours in it and don't know whats wrong. Really strange.

I'll provide my Dockerfile here if my current trial with simplified build already stucks. May be you or someone else will see what's going wrong.

**Comment by typoworx-de** [comment] 2023-02-24 10:05
@mlocati still having problems to install gd during Dockerfile build. 

```
FROM php:8.1-fpm-bullseye

RUN \
  apt-get update \
  && apt-get -y upgrade \
  && apt-get install --no-install-recommends -y

RUN \
  --mount=type=bind,from=mlocati/php-extension-installer:1.5,source=/usr/bin/install-php-extensions,target=/usr/local/bin/install-php-extensions \
  set -ex; \
  IPE_GD_WITHOUTAVIF=1 install-php-extensions gd;
```

Error from Dockerfile build:
```
#21 97.33 make: *** No rule to make target 'intl', needed by 'all'.  Stop.
#21 97.33 make: *** Waiting for unfinished jobs....
#21 97.33 gd.c:28:10: fatal error: php.h: No such file or directory
#21 97.33    28 | #include "php.h"
#21 97.33       |          ^~~~~~~
#21 97.33 compilation terminated.
#21 97.34 make: *** [<builtin>: gd] Error 1
```

and now the strange part... running the same command in a successful build container (build without the RUN-Statement for 'install-php-extensions'), the command works! :-/

I have a very similar same issue with zip-extension, but there the error looks like this:
```
#22 92.30 + docker-php-ext-install -j12 zip
#22 92.30 make: *** No rule to make target 'zip', needed by 'all'.  Stop.
------
failed to solve: executor failed running [/bin/bash -c set -ex; IPE_GD_WITHOUTAVIF=1   install-php-extensions zip]: exit code: 2
```
(also mentioned here: #625)

and also for zip extension the build works fine in a running container. same build, but without any custom-build extensions.

I can't figure out what's wrong. Anything I'm doing wrong?!

**Comment by typoworx-de** [comment] 2023-02-24 13:33
I've given up for now ... after nearly 4 frustrating days. Tried using ```install-php-extensions``` with separate RUN statement for each wanted PHP-Extension and also one RUN statement with all extensions at once given to install-php-extensions.

But none of these worked for me using dockerhub-image php:8.1-fpm-bullseye nor php:8.1-fpm-buster (both are debian's version 11 and 10).

I don't know whats wrong but it feels like something isn't working as expected here :-/

**Comment by mlocati** [comment] 2023-03-14 15:00
Closing as it's likely a duplicate of #697

**Closed by mlocati** 2023-03-14 15:00 UTC
Labels: bug
