### ISSUE TITLE
igbinary version 3.2.2RC1-beta is not available

### ISSUE THREAD

**Issue by palpalani** [mlocati/docker-php-extension-installer#248] opened 2021-01-12 03:54 UTC
```
### INSTALLING REMOTE MODULE igbinary ###
--
1008 | - Installing igbinary (latest-stable): Downloading (connecting...)···························Downloading (0%)           ···························Downloading (65%)·················Downloading (75%)·················Downloading (100%)
1009 |  
1010 | In VersionParser.php line 176:
1011 |  
1012 | Invalid version string "3.2.2RC1-beta"
```

New version released `3.2.2RC1`.

**Comment by mlocati** [comment] 2021-01-12 06:58
It's yet another prpblem caused by pickle. I wish we have a valid alternative...

**Comment by mlocati** [comment] 2021-01-14 07:44
The only solution at the moment is to specify the igbinary version explicitly:

```sh
install-php-extensions  igbinary-3.2.1
```

**Comment by mvorisek** [comment] 2021-01-16 12:56
Can this be fixed in this repo, eg. when no specific version is defined, use `3.2.1`. With comment, it should be removed in the future once the issue (incl. link, it is a pickle issue?) is resolved.

**Closed** 2021-01-16 20:33 UTC
