### ISSUE TITLE
Can't install gd extension

### ISSUE THREAD

**Issue by sluther** [mlocati/docker-php-extension-installer#896] opened 2024-03-12 05:52 UTC
### Version of install-php-extensions

v2.2.2

### Error description

I get the following error when trying to build:

```
#9 30.32 libtool: link: `libgd/gd_pixelate.lo' is not a valid libtool object
#9 30.32 make: *** [Makefile:338: gd.la] Error 1
#9 ERROR: process "/bin/sh -c chmod +x /usr/local/bin/install-php-extensions &&     install-php-extensions gd exif intl" did not complete successfully: exit code: 2
```

This only seems to happen when I build for the linux/amd64 platform (which I need to do, as I'm running docker on an ARM Mac):

`docker buildx build --progress=plain --no-cache --platform=linux/amd64 .`

### Docker image

php:8.2-fpm-alpine

### Minimal Dockerfile

```Dockerfile
FROM php:8.2-fpm-alpine

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions gd exif intl
```

**Comment by mlocati** [comment] 2024-03-15 16:35
I can't replicate this issue

**Comment by sluther** [comment] 2024-03-15 20:15
I just tried again and now I am getting this error:

```
fontl.lo  -MMD -MF libgd/gdfontl.dep -MT libgd/gdfontl.lo
32.39 cc: warning: : linker input file unused because linking not done
32.39 cc: error: : linker input file not found: No such file or directory
32.40 make: *** [Makefile:240: libgd/gd_webp.lo] Error 1
32.40 make: *** Waiting for unfinished jobs....
```

Is this caused by some sort of issue with my environment? I am on the latest version of Docker as well (Docker Desktop v4.28.0)

**Comment by hcpss-banderson** [comment] 2024-03-15 20:32
I can reproduce. Started getting something similar with bcmath when i switched from an intel mac to my new M3. Tried your Dockerfile and I get your same error. Maybe and issue in the extensions themselves.

**Comment by pionl** [comment] 2024-03-16 16:15
Hi there, same, im stuck too. It was working some time ago.

**I managed to find out why, it was due the php8.1.27 version, when reverting back to php8.1.26 it started working again**

---

I've got the same issue on Apple silicon and using `linux/amd64` with gd extension. 

```bash
install-php-extensions ctype intl redis pdo pdo_mysql gd imagick exif mbstring json xml tokenizer xdebug opcache zip
```

Tried to lower the version of install-php-extension and no help :)

Version [v2.1.84](https://github.com/mlocati/docker-php-extension-installer/releases/tag/2.1.84)
```
60.84 cc: warning: : linker input file unused because linking not done
60.84 cc: error: : linker input file not found: No such file or directory
60.84 make: *** [Makefile:215: intl_convert.lo] Error 1
60.84 make: *** Waiting for unfinished jobs....
```

Version [v2.2.3](https://github.com/mlocati/docker-php-extension-installer/releases/tag/2.2.3) different error

```
55.83 mkdir collator/.libs
55.83 mkdir collator/.libs
55.83 mkdir collator/.libs
55.83 mkdir collator/.libs
55.84 mkdir collator/.libs
55.84 mkdir: can't create directory 'collator/.libs': File exists
55.84 mkdir: can't create directory 'collator/.libs': File exists
55.84 mkdir: can't create directory 'collator/.libs': File exists
55.84 mkdir: can't create directory 'collator/.libs': File exists
55.87 cc: warning: : linker input file unused because linking not done
55.87 cc: error: : linker input file not found: No such file or directory
55.88 make: *** [Makefile:236: collator/collator_attr.lo] Error 1
```

If i removed gd, not success ;) Using php-8.1.27-cli-alpine image

If I remove intl, it crashes on redis... :)

**Comment by cyppe** [comment] 2024-03-17 17:31
Same error here. 

As soon as I add 'gd' some other extension fails.

A part of my Dockerfile as example where you can (hopefully) reproduce it too. 

It worked fine last week so something must have broken latest days.

```
FROM dunglas/frankenphp:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
	acl \
	file \
	gettext \
	git \
	procps \
	htop \
	&& rm -rf /var/lib/apt/lists/*

RUN set -eux; \
	install-php-extensions \
		@composer \
		opcache \
		zip \
		pcntl \
		redis \
		igbinary \
		mysqli \
		pdo_mysql \
		exif \
		bcmath \
                 sockets \
                 gd \
	;

# https://getcomposer.org/doc/03-cli.md#composer-allow-superuser
ENV COMPOSER_ALLOW_SUPERUSER=1

```


Removing 'gd' makes everything work again.


**Error is usually something like this:**

```
78.62 cc: warning: : linker input file unused because linking not done
78.62 cc: error: : linker input file not found: No such file or directory
78.62 make: *** [Makefile:235: zend_accelerator_blacklist.lo] Error 1
78.62 make: *** Waiting for unfinished jobs....
```

**Comment by cyppe** [comment] 2024-03-17 17:35
Update: Probably same as previous mentions, there has been a new php 8.3 release since my last successful build. Will try to lock it to 8.3.3 instead of 8.3.4.

**Comment by sluther** [comment] 2024-03-18 03:17
Unfortunately, I need to use php 8.2 for now, otherwise I'd have tried 8.3+. Also worth noting, but this works for me just fine with `php:8.2-fpm` and `php:8.2-fpm-bookworm` (not surprising as both of these are the same). It also fails with `php:8.2-fpm-bullseye` and `php:8.2-fpm-alpine3.18` and `php:8.2-fpm-alpine3.19`. I'm trying to use the alpine image as it's much smaller than the others.

**Comment by hcpss-banderson** [comment] 2024-03-18 18:53
I've been trying to cross compile php images with extensions without the use of this project to wildly inconsistent results. Different extensions giving different errors. I think we may just not be understanding how multiplatform building works.

Here is a workaround from [this post](https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/):

```
FROM --platform=$BUILDPLATFORM php:8.2-fpm-alpine

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions gd exif intl
```

It seems strange to have to explicitly tell docker that I want to use the base image for my target architecture, but i guess we do.

**Comment by marcispauls** [comment] 2024-03-19 14:11
the issue seems only on arm64 on x64 all seems fine

**Comment by mlocati** [comment] 2024-03-19 17:15
So, the issue is not related to `install-php-extensions` and can be fixed by using

```Dockerfile
FROM --platform=$BUILDPLATFORM php:whatever
```

right? If so, I'd close this issue...

**Comment by sluther** [comment] 2024-03-19 17:17
I will test that when I get home and report back, though I don't believe that will fix the issue (I had tried specifying the `--platform` already and it was failing then, too).

**Comment by pionl** [comment] 2024-03-19 18:22
It works, but I'm unable to build amd64 flavor now and I was unable to seutp buildx that uses the `$BUILDPLATFORM`

**Comment by sluther** [comment] 2024-03-20 13:43
I have confirmed that while setting `--platform=$BUILDPLATFORM` prevents the error during build, I am unable to actually run the docker image on my server, so unfortunately, this is not a fix. Setting `--platform=linux/amd64` unfortunately does not work, and that's the architecture I need (building on an M2 mac but running on a linux/amd64 server).

**Comment by mlocati** [comment] 2024-03-20 13:48
> I am unable to actually run the docker image on my server

What's the error?

**Comment by sluther** [comment] 2024-03-20 14:21
The error I'm getting is:
```
php-fpm-1  | exec /usr/local/bin/docker-php-entrypoint: exec format error
php-fpm-1 exited with code 1
```

**Comment by hcpss-banderson** [comment] 2024-03-20 18:53
Yeah i get that too. I was definitely wrong about BUILDPLATFORM. It might be TARGETPLATFORM, but i am not convinced of that now either.

If we want to demonstrate that this is an issue with install-php-extensions, we need to show:

1. We can build a php image with gd on apple silicone that targets amd64 **without install-php-extensions**
2. We cannot build a similar php image **with install-php-extensions**

I can't get 1 working.

I think this is a minimal dockerfile:

```dockerfile
FROM php:8.2-fpm-alpine

RUN apk add --no-cache --virtual \
    build-essentials \
    zlib-dev \
    g++ \
    make \
    automake \
    autoconf \
    libpng-dev \
    libjpeg-turbo-dev
RUN docker-php-ext-configure gd --enable-gd --with-jpeg
RUN docker-php-ext-install gd
```
 @sluther can you build that for amd64?

**Comment by hcpss-banderson** [comment] 2024-03-20 19:39
Thanks to [this comment on a similar issue](https://github.com/docker-library/php/issues/1424#issuecomment-1700504649), I think I have this fixed.

It seems that while Rosetta allows us to run amd64 images on our arm64 macs, it is messing up multiplatform building. So turn it off:

Dashboard > Settings > General

Uncheck *Use Rosetta for x86_64/amd64 emulation on Apple Silicon*

I can now consistently build the amd64 image and run it on my x86 server.

**Comment by mlocati** [comment] 2024-03-20 21:50
@sluther @pionl @cyppe can you confirm this is working for you too?

**Comment by sluther** [comment] 2024-03-20 22:01
@mlocati yep. I can confirm the above fix worked for me. I was able to build on my mac and deploy to my amd64 server without any issues.

@hcpss-banderson Thanks a ton. Great find!

**Comment by pionl** [comment] 2024-03-22 16:33
@hcpss-banderson wow, I did not expect this, the description makes me think it will work thanks to the option. Thanks for finding this!

@mlocati I will test it on Monday, I did not have the time to make it this week. 

Thanks all!

**Comment by pionl** [comment] 2024-03-26 22:38
Hey all. If I disable the `Use Rosetta for x86_64/amd64 emulation on Apple Silicon` I'm unable to run correctly any images with `--platform=linux/amd64` -> I need to set amd64 for chrome. 

If I uncheck roseta, build an image, then i can start the container but it crashes on launching chrome.

Then I've tried to update the PHP related images with unchecked rosetta and I did not manage to setup the docker to support buildx. I'll try next time then.

```
❯ docker buildx build --platform linux/amd64,linux/arm64 . -t pionl/docker-php-laravel-ci:8.2-node-20-test
[+] Building 0.0s (0/0)                                                                                                              docker:desktop-linux
ERROR: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-multi-platform/
```

<img width="854" alt="Snímek obrazovky 2024-03-26 v 23 36 02" src="https://github.com/mlocati/docker-php-extension-installer/assets/1878831/7a3756b8-ae6f-4b9b-8458-593e7d0e625d">


FYI: I can build 8.1.26 without problem, 8.1.27 fails (or PHP 8.2+).

**Comment by debreczeniandras** [comment] 2024-10-16 09:33
My issue is somewhat similar, but the other way around: I am using linux to build an ARM image.
I was able to see what the exit code actually means: 

I am getting segmentation fault during the installation of libaom.
```shell
#23 255.6 FAILED: CMakeFiles/aom_av1_encoder_neon_intrinsics.dir/av1/encoder/arm/neon/av1_fwd_txfm2d_neon.c.o 
#23 255.6 /usr/bin/cc  -I../ -I. -I../apps -I../common -I../examples -I../stats -I../third_party/libyuv/include -O3 -DNDEBUG -std=c99 -Wall -Wdisabled-optimization -Wextra -Wfloat-conversion -Wformat=2 -Wimplicit-function-declaration -Wlogical-op -Wpointer-arith -Wshadow -Wsign-compare -Wtype-limits -Wuninitialized -Wunused -Wvla -Wstack-usage=100000 -Wundef -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fPIC -MD -MT CMakeFiles/aom_av1_encoder_neon_intrinsics.dir/av1/encoder/arm/neon/av1_fwd_txfm2d_neon.c.o -MF CMakeFiles/aom_av1_encoder_neon_intrinsics.dir/av1/encoder/arm/neon/av1_fwd_txfm2d_neon.c.o.d -o CMakeFiles/aom_av1_encoder_neon_intrinsics.dir/av1/encoder/arm/neon/av1_fwd_txfm2d_neon.c.o -c ../av1/encoder/arm/neon/av1_fwd_txfm2d_neon.c
#23 255.6 cc: internal compiler error: Segmentation fault signal terminated program cc1
```

The issue is also reproducible locally:

Dockerfile:
```Dockerfile
ARG PHP_EXTENSION_INSTALLER=2.5.2
FROM mlocati/php-extension-installer:${PHP_EXTENSION_INSTALLER} AS php-extensions-installer
FROM php:8.2-apache-bookworm
COPY --from=php-extensions-installer /usr/bin/install-php-extensions /usr/bin/
RUN set -eux; install-php-extensions gd
```

Then build for ARM: 
```shell
docker buildx create --driver=docker-container --name=emu --platform linux/arm64
docker buildx use emu
docker buildx build --pull --platform linux/arm64  .
```
---

I also tried temporarily updating libaom to version 3.10.0 (also for the ARM environment), as the mentioned bug has already been fixed. That hasn't helped either.

**Comment by mlocati** [comment] 2024-10-16 13:06
@debreczeniandras could you check if the changes made by #996 fix your problem?

**Comment by debreczeniandras** [comment] 2024-11-13 09:21
@mlocati No, unfortunately the issue still persists in a multi-arch build (with QEMU). I am still investigating and will report back once I found a solution.

**Comment by alazycoder101** [comment] 2024-12-10 21:57
I'm having the similar issue when trying to run `docker-php-ext-install -j$(nproc) opcache` on php:8.0-fpm 
`docker run --rm -it --platform linux/amd64 php:8.0-fpm  bash`

```bash
❯ colima status -e
INFO[0000] colima is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/lazycoder/.colima/default/docker.sock
INFO[0000] cpu: 2
INFO[0000] mem: 10GiB
INFO[0000] disk: 60GiB
```

```bash
 cc -I. -I/usr/src/php/ext/opcache -I/usr/src/php/ext/opcache/include -I/usr/src/php/ext/opcache/main -I/usr/src/php/ext/opcache -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -c /usr/src/php/ext/opcache/Optimizer/zend_cfg.c  -fPIC -DPIC -o Optimizer/.libs/zend_cfg.o
/bin/bash /usr/src/php/ext/opcache/libtool --mode=compile cc -I. -I/usr/src/php/ext/opcache -I/usr/src/php/ext/opcache/include -I/usr/src/php/ext/opcache/main -I/usr/src/php/ext/opcache -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -c /usr/src/php/ext/opcache/Optimizer/zend_dfg.c -o Optimizer/zend_dfg.lo
/bin/bash /usr/src/php/ext/opcache/libtool --mode=compile cc -I. -I/usr/src/php/ext/opcache -I/usr/src/php/ext/opcache/include -I/usr/src/php/ext/opcache/main -I/usr/src/php/ext/opcache -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -c /usr/src/php/ext/opcache/Optimizer/dfa_pass.c -o Optimizer/dfa_pass.lo
 cc -I. -I/usr/src/php/ext/opcache -I/usr/src/php/ext/opcache/include -I/usr/src/php/ext/opcache/main -I/usr/src/php/ext/opcache -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -c /usr/src/php/ext/opcache/Optimizer/zend_dfg.c  -fPIC -DPIC -o Optimizer/.libs/zend_dfg.o
/usr/src/php/ext/opcache/libtool: line 1330: 27173 Segmentation fault      (core dumped) cc -I. -I/usr/src/php/ext/opcache -I/usr/src/php/ext/opcache/include -I/usr/src/php/ext/opcache/main -I/usr/src/php/ext/opcache -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -c /usr/src/php/ext/opcache/Optimizer/zend_dfg.c -fPIC -DPIC -o Optimizer/.libs/zend_dfg.o
make: *** [Makefile:275: Optimizer/zend_dfg.lo] Error 1
make: *** Waiting for unfinished jobs....
 cc -I. -I/usr/src/php/ext/opcache -I/usr/src/php/ext/opcache/include -I/usr/src/php/ext/opcache/main -I/usr/src/php/ext/opcache -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -c /usr/src/php/ext/opcache/Optimizer/dfa_pass.c  -fPIC -DPIC -o Optimizer/.libs/dfa_pass.o
```

Even though I can get the coredump for this error but no idea where the problem is.
```bash
/usr/src/php/ext/opcache# ls -lh core
-rw------- 1 root root 1.8M Dec 10 21:49 core
```

**Comment by mlocati** [comment] 2024-12-12 00:10
Closing since this issue is not related to the install-php-extensions script.

**Closed by mlocati** 2024-12-12 00:10 UTC
Labels: bug
