### ISSUE TITLE
GD broken for PHP 8.1

### ISSUE THREAD

**Issue by prilka** [mlocati/docker-php-extension-installer#522] opened 2022-03-09 16:52 UTC
### Version of install-php-extensions

1.4.17

### Error description

The installation of ext-gd fails for PHP 8.1 (debian and alpine).

>...
Installing libavif
-- The C compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- libavif: Enabling warnings for GCC
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'libyuv'
--   No package 'libyuv' found
-- libavif: libyuv (1812) found; libyuv-based fast paths enabled.
-- libavif: Codec enabled: aom (encode/decode)
-- Checking for module 'aom'
--   Found aom, version 3.1.2
-- Found aom: /usr/local/lib/libaom.so (found version "3.1.2") 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/src/tmp.6VuaXHSwW2/libavif-0.9.2/build
Scanning dependencies of target avif
[ 18%] Building C object CMakeFiles/avif.dir/src/alpha.c.o
[ 18%] Building C object CMakeFiles/avif.dir/src/avif.c.o
[ 18%] Building C object CMakeFiles/avif.dir/src/colr.c.o
[ 25%] Building C object CMakeFiles/avif.dir/src/mem.c.o
[ 31%] Building C object CMakeFiles/avif.dir/src/diag.c.o
[ 37%] Building C object CMakeFiles/avif.dir/src/io.c.o
[ 43%] Building C object CMakeFiles/avif.dir/src/obu.c.o
[ 50%] Building C object CMakeFiles/avif.dir/src/rawdata.c.o
[ 56%] Building C object CMakeFiles/avif.dir/src/read.c.o
[ 62%] Building C object CMakeFiles/avif.dir/src/reformat.c.o
[ 68%] Building C object CMakeFiles/avif.dir/src/reformat_libyuv.c.o
[ 75%] Building C object CMakeFiles/avif.dir/src/stream.c.o
In file included from /usr/include/libyuv/convert.h:19,
                 from /usr/include/libyuv.h:16,
                 from /tmp/src/tmp.6VuaXHSwW2/libavif-0.9.2/src/reformat_libyuv.c:36:
/usr/include/libyuv/convert_argb.h:1947:28: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 1947 |                            FilterMode filter);
      |                            ^~~~~~~~~~
      |                            FilterModeEnum
/usr/include/libyuv/convert_argb.h:1962:28: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 1962 |                            FilterMode filter);
      |                            ^~~~~~~~~~
      |                            FilterModeEnum
/usr/include/libyuv/convert_argb.h:1977:28: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 1977 |                            FilterMode filter);
      |                            ^~~~~~~~~~
      |                            FilterModeEnum
/usr/include/libyuv/convert_argb.h:1992:28: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 1992 |                            FilterMode filter);
      |                            ^~~~~~~~~~
      |                            FilterModeEnum
/usr/include/libyuv/convert_argb.h:2007:28: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 2007 |                            FilterMode filter);
      |                            ^~~~~~~~~~
      |                            FilterModeEnum
/usr/include/libyuv/convert_argb.h:2022:28: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 2022 |                            FilterMode filter);
      |                            ^~~~~~~~~~
      |                            FilterModeEnum
/usr/include/libyuv/convert_argb.h:2040:33: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 2040 |                                 FilterMode filter);
      |                                 ^~~~~~~~~~
      |                                 FilterModeEnum
/usr/include/libyuv/convert_argb.h:2058:33: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 2058 |                                 FilterMode filter);
      |                                 ^~~~~~~~~~
      |                                 FilterModeEnum
/usr/include/libyuv/convert_argb.h:2076:33: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 2076 |                                 FilterMode filter);
      |                                 ^~~~~~~~~~
      |                                 FilterModeEnum
/usr/include/libyuv/convert_argb.h:2094:33: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 2094 |                                 FilterMode filter);
      |                                 ^~~~~~~~~~
      |                                 FilterModeEnum
/usr/include/libyuv/convert_argb.h:2107:28: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 2107 |                            FilterMode filter);
      |                            ^~~~~~~~~~
      |                            FilterModeEnum
/usr/include/libyuv/convert_argb.h:2120:28: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 2120 |                            FilterMode filter) ;
      |                            ^~~~~~~~~~
      |                            FilterModeEnum
/usr/include/libyuv/convert_argb.h:2133:28: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 2133 |                            FilterMode filter);
      |                            ^~~~~~~~~~
      |                            FilterModeEnum
/usr/include/libyuv/convert_argb.h:2146:28: error: unknown type name 'FilterMode'; did you mean 'FilterModeEnum'?
 2146 |                            FilterMode filter);
      |                            ^~~~~~~~~~
      |                            FilterModeEnum
make[2]: *** [CMakeFiles/avif.dir/build.make:212: CMakeFiles/avif.dir/src/reformat_libyuv.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:133: CMakeFiles/avif.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

Versions:
```bash
root@a31f16c03420:/# php -v
PHP 8.1.3 (cli) (built: Mar  3 2022 07:21:51) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies
root@a31f16c03420:/# 
root@a31f16c03420:/# install-php-extensions  
install-php-extensions v.1.4.17
root@a31f16c03420:/# 
```

It's very easy to reproduce
```bash
docker run --rm -ti php:8.1 bash
# run
curl -Lo /usr/local/bin/install-php-extensions 'https://github.com/mlocati/docker-php-extension-installer/releases/download/1.4.17/install-php-extensions' && chmod +x /usr/local/bin/install-php-extensions 
install-php-extensions gd
```

### Docker image

php:8.1-cli

### Minimal Dockerfile

```Dockerfile
FROM php:8.1
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
```

**Comment by mavaddat** [comment] 2022-03-09 18:54
Same on php:8.1-fpm

```Dockerfile
FROM php:8.1-fpm
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions gd
```

**Comment by mavaddat** [comment] 2022-03-09 19:08
Workaround:

```shell
echo 'deb http://deb.debian.org/debian bullseye-backports main' > /etc/apt/sources.list.d/bullseye-backports.list 
apt update
apt install -t bullseye-backports libyuv-dev
install-php-extensions gd
```

In Dockerfile:

```Dockerfile
FROM php:8.1-fpm
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions \
  && echo 'deb http://deb.debian.org/debian bullseye-backports main' > /etc/apt/sources.list.d/bullseye-backports.list \
  && apt install -t bullseye-backports libyuv-dev -y
  && install-php-extensions gd
```

**Comment by damosse31** [comment] 2022-03-09 20:02
My workaround is to install gd extension with built-in _docker-php-ext-install_ :

```dockerfile
FROM php:8.1-apache

# Install some required packages for gd extension
RUN apt-get update && apt-get install -y zlib1g zlib1g-dev libpng-dev

# Install php gd extension
RUN docker-php-ext-install gd
```

**Comment by nuvolapl** [comment] 2022-03-09 20:05
The AVIF format is problematic. I don't use it so I simple disable it with `IPE_GD_WITHOUTAVIF` environment variable.

```dockerfile
RUN IPE_GD_WITHOUTAVIF=1 install-php-extensions gd-stable
```

See: https://github.com/mlocati/docker-php-extension-installer#configuration


gd | IPE_GD_WITHOUTAVIF=1 | Since PHP 8.1, gd supports the AVIF format. Enabling it requires  compiling libaom/libdav1d/libyuv/libavif, which is time-consuming. You  can disable AVIF support by setting this environment variable
-- | -- | --

**Comment by mlocati** [comment] 2022-03-09 20:06
While I try to find some time to fix the issue, you can set this environment variable
IPE_GD_WITHOUTAVIF=1

See https://github.com/mlocati/docker-php-extension-installer#configuration

**Comment by prilka** [comment] 2022-03-10 09:57
I found out that if I install the package `livavif-dev` from the official repositories, the compilation process works without errors. Works on Debian and Alpine. On Debian additionally I had to create a symlink for `/usr/lib/libavif.so` so that your Script will detect its presence in `isLibavifInstalled`
```
ln -s /usr/lib/x86_64-linux-gnu/libavif.so.9 /usr/lib/libavif.so
```

Maybe this will help somehow

**Comment by mlocati** [comment] 2022-03-10 15:04
@prilka Could you try to run [this PHP script](https://github.com/mlocati/docker-php-extension-installer/blob/1.4.17/scripts/tests/gd) when you use the package `libavif-dev` instead of building it?

**Comment by mlocati** [comment] 2022-03-10 15:17
Here's the result of some tests I did on the Debian versions that come with PHP 8.1 (buster and bullseye):

| Package | buster | bullseye |
|---|---|---|
| libdav1d-dev | buster-backports + apt install | apt install |
| libavif-dev | buster-backports + apt install | apt install |
| libyuv-dev | compile source code | bullseye-backports + apt install |
| libaom | compile source code | compile source code |
| Result of scripts/tests/gd | Checking format avif... Segmentation fault | Checking format avif... Error 2: imageavif(): avif error - Could not encode image: No codec available |

**Comment by prilka** [comment] 2022-03-13 17:00
> @prilka Could you try to run [this PHP script](https://github.com/mlocati/docker-php-extension-installer/blob/1.4.17/scripts/tests/gd) when you use the package `libavif-dev` instead of building it?

Output ist this:
> Creating sample image... done.
Checking format gd2... done.
Checking format gif... done.
Checking format jpeg... done.
Checking format png... done.
Checking format wbmp... done.
Checking format webp... done.
Checking format wbmp... done.
Checking format xbm... done.
Checking format xpm... skipping tests since PHP can't save images to that format.
Checking format gd... done.
Checking format bmp... done.
Checking format avif... imageavif() created an empty file

**Comment by mlocati** [comment] 2022-03-13 18:58
> Checking format avif... imageavif() created an empty file

So, it seems that this approach doesn't work...

**Comment by mlocati** [comment] 2022-03-14 16:02
It seems that this issue is caused by https://chromium.googlesource.com/libyuv/libyuv/+/ebb27d69160b3768187bb8372c01dcbf5e61785a and has already been fixed by https://chromium.googlesource.com/libyuv/libyuv/+/25d0a5110be796eef47004412baf43333d9ecf26

We should really avoid using a branch name when downloading external data.

**Comment by mlocati** [comment] 2022-03-14 16:21
See #524

**Closed by mlocati** 2022-03-14 16:21 UTC
Labels: bug

**Comment by prilka** [comment] 2022-03-16 14:55
I can confirm, that everything is working fine now with v1.4.18 👍 

Thanks for the quick fix!
